# Relay all ahelp messages
discord.ahelp_webhook: "DISCORD_AHELP_WEBHOOK_URL"

# Round end updates
discord.round_update_webhook: "DISCORD_ROUNDUPD_WEBHOOK_URL"
discord.round_end_role: "ROUNDEND_ROLE_ID"
