- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
<<<<<<< HEAD
    roleType: MinorAntagonist
=======
    roleType: SoloAntagonist
    subtype: role-subtype-abductor
>>>>>>> goob/master
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorAgent
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorAgentAntag
<<<<<<< HEAD
    roleType: MinorAntagonist
=======
    roleType: TeamAntagonist
    subtype: role-subtype-abductor
>>>>>>> goob/master
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorScientist
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorScientistAntag
<<<<<<< HEAD
    roleType: MinorAntagonist
=======
    roleType: TeamAntagonist
    subtype: role-subtype-abductor
>>>>>>> goob/master
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: Abductee Role
  components:
  - type: MindRole
    roleType: FreeAgent
    antagPrototype: AbductorVictimAntag
    subtype: role-subtype-abductor-victim
  - type: AbductorVictim
