- type: entity
  parent: BaseMindRoleAntag
  id: DevilMindRole
  name: Devil Role
  components:
  - type: MindRole
    antagPrototype: Devil
    exclusiveAntag: true
<<<<<<< HEAD
    roleType: MinorAntagonist
=======
    roleType: SoloAntagonist
    subtype: role-subtype-devil
>>>>>>> goob/master
  - type: DevilRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-changeling
  - type: ChangelingRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: Heretic Role
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-heretic
  - type: HereticRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBrainwashed
  name: Brainwashed Role
  components:
  - type: MindRole
    antagPrototype: Mindcontrolled
    exclusiveAntag: true
    roleType: Familiar
    subtype: role-subtype-brainwashed
  - type: MindcontrolledRole
